language: go
sudo: false
go:
- 1.9.x

env:
  - DEP_VERSION="0.3.2"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - make get_dep

before_deploy:
- git config --local user.name "dfredell"
- git config --local user.email "dan.fredell@gmail.com"
- git tag "$(date +'%Y-%m-%dT%H-%M-%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MCQRRYZ5iv42p+ywSb46Uuumz24yzXxtJjloCyHJaJECTmfmeXp6bSvdkPCANmEgcsepAS+QWxIrMb1X/PhWwm+TPWDSA9Lxmdi/+5mph41xAx3f+mv7AgmdHmLXiyVGFm0br806EFFC13ojfLjXJf6tXC+BJ8Ztt8RL2YgHE4ZzxDJrZYKhlBOaDSPii13jCipaA5mVIpYf2S3k0xqgu6l/RGTeyrnqHsm2vifocBnWcKwDUdKLLwxXPMfYxgyQdVaMgJvkVnkAS5t9Imh0Ne2ej1a7biWlk8uF+BaAU2l+dhIop0T6P+/gLR97HaI/lDkOwMYPx/OXMqcgo+3XH98fACjUV/UGBTF5fZl+OjE7iAVEC3kD8VzjNMLxlCdNPf8H/gHXpIkbRc9HFAZvrrMLwEr+jLWB1BL5xFbHxz3k9pB4rQ6IgU7JxF0RRu0fnauhJuGdd1OlXwCJ/FxoOy3JVG2+UJJ+tMg4h9+yFu/xthbnQQcN/vxuIKkS42nwDqq/m8Dse58m3XULR+TMwGabcVaiQHCcNKutonWPIQ9KMDm2iUWZOCtxc1178MY65Z6W4JpQaTGIlwXkMC7g5dMBS6VPdGX3mbnF98TlLKDfaRm3tggtWlfS0swt4xcdDwl8VwAeTZew7aaj/NYs3rr6shl0h0UD/lxEfj5Psrk=
  file: "minio_exporter"
  on:
    branch: master
